FROM golang:1.12-alpine3.10

RUN apk update && apk add gcc git 
WORKDIR /
COPY go.mod .
COPY . .
RUN go build ./...
RUN go test ./...
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

CMD ["./app"]