apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sample-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
         app: sample-app
    spec: 
      containers:
      - name: sample-app
        image: gcr.io/google_containers/defaultbackend:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: service-key
          mountPath: /root/key.json
          subPath: key.json
        env:
        - name: "AUTH_TOKEN"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: webhook_token
        - name: "SLACK_TOKEN"
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: slack_token
      volumes:
      - name: service-key
        secret:
          secretName: my-secret
          items:
          - key: service_account_key
            path: key.json
