server:
  port: 8088

spring:
  application.name: seat-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saga_db
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

eventuatelocal.kafka.bootstrap.servers: localhost:9092
eventuatelocal.zookeeper.connection.string: localhost:2181
