# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # box 1 - kamailio
  config.vm.define "kamailio-vm" do |instance|
    instance.vm.box = "bento/centos-8"
    instance.vm.hostname = "kamailio"
    instance.vm.network "public_network", bridge: "wlo1", ip:"192.168.1.20", netmask:"255.255.0.0"

    instance.vm.provider "virtualbox" do |v|
      v.name = "kamailio-vm"
    end
  end  
  
  # box 2 - coturn
  config.vm.define "coturn-vm" do |instance|
    instance.vm.box = "bento/centos-8"
    instance.vm.hostname = "coturn"
    instance.vm.network "public_network", bridge: "wlo1", ip:"192.168.1.22", netmask:"255.255.0.0"

    instance.vm.provider "virtualbox" do |v|
      v.name = "coturn-vm"
    end
  end
end
