version: "3"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "hex_test"
    volumes: 
      - ./testdb:/docker-entrypoint-initdb.d
    ports:
      - "3336:3306"

  rest: 
    build: .
    environment:
      DB_DRIVER: "mysql"
      DS_NAME: "root:password@tcp(db:3306)/hex_test"
      MYSQL_HOST: "db"
      MYSQL_PASSWORD: "password"
      MYSQL_DB: "hex_test"
      MYSQL_USER: "root"
      MYSQL_PORT: "3306"
    depends_on:
      - db
    ports:
      - "3000:3000"
    command: ["go", "test", "-v", "./..."]