
Vagrant.configure("2") do |config|
  
  
    config.vm.provision "shell", inline: <<-SHELL
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
      systemctl reload sshd
      echo -e "admin\nadmin" | passwd root >/dev/null 2>&1
  SHELL
  
      #haproxy load balancer node
      config.vm.define "haproxy" do |node|
          node.vm.box = "bento/ubuntu-20.04"
          node.vm.hostname = "haproxy"
          node.vm.network "private_network", ip: "172.16.16.200"
          node.vm.provider "virtualbox" do |v|
            v.name = "haproxy"
            v.memory = 1024
            v.cpus = 1
          end
      end
      
      #k8s nodes
      (1..3).each do |i|
          config.vm.define "master#{i}" do |node|
            node.vm.box = "bento/ubuntu-20.04"
            node.vm.hostname = "master#{i}"
            node.vm.network "private_network", ip: "172.16.16.21#{i}"
            node.vm.provider "virtualbox" do |v|
              v.name = "master#{i}"
              v.memory = 2048
              v.cpus = 2
            end
          end
      end
      
      (1..3).each do |i|
          config.vm.define "worker#{i}" do |node|
            node.vm.box = "bento/ubuntu-20.04"
            node.vm.hostname = "worker#{i}"
            node.vm.network "private_network", ip: "172.16.16.22#{i}"
            node.vm.provider "virtualbox" do |v|
              v.name = "worker#{i}"
              v.memory = 1024
              v.cpus = 1
            end
          end
      end
    
  end